### ISSUE TITLE
Let IHostPool extend Collection<IHost>

### ISSUE THREAD

**Issue by 8191** [xLeitix/jcloudscale#13]
It would be nice if `IHostPool` would extend `Collection<IHost>`, so that one can access the hosts without the need to manually iterate through them and many built-in methods of the Java library can be used. E.g.

```
IHost bestHost = Collections.min(hostPool.getHosts(), new Comparator<IHost>() {
    @Override
    public int compare(IHost host1, IHost host2) {
        return Integer.compare(host1.getCloudObjectsCount(), host2.getCloudObjectsCount());
    }
});
```

**Comment by rstzab** [comment]
Extending of collection interface in IHostPool might be an overkill: it provides many methods that hardly make any sense for the hostpool class (e.g., add, addAll, remove,removeAll, toArray...)

However, we may consider returning hosts (getHosts() method currently returns Iterable<IHost>) as [unmodifiable collection](http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#unmodifiableCollection%28java.util.Collection%29). From the code you shown, I suppose that was your wish. ;-)

**Comment by 8191** [comment]
In fact many methods of the `Collection<T>` interface are marked optional, i.e. they may throw a `UnsupportedOperationException`. This applies as far as I can see to all modifying operation.

But returning a `Collection` object by `IHostPool#getHosts()` would also solve the need. ;)

**Comment by rstzab** [comment]
getHosts() method of IHostPool interface returns Unmodifiable Collection as of JCloudScale 0.4.5-SNAPSHOT.
Code/documentation on github will be updated at mid June.
