### ISSUE TITLE
The private static nested classes in at.ac.tuwien.infosys.jcloudscale.utility.CgLibUtil can't be shut up with logging configuration

### ISSUE THREAD

**Issue by xLeitix** [xLeitix/jcloudscale#15]
CgLibUtil has two private static nested classes: JCloudScaleCloudObjectHandler and JCloudScaleReferenceHandler. The former logs to its own logger (line 141 - 143) when trying to invoke a non-deployed object.

I have a case where I don't care about this, but I seem to be unable to make the config ignore this warning because I cannot import a private class. Hence, 

.withLoggingCustom(CgLibUtil.JCloudScaleObjectLogger.class, Level.OFF)

will not work. There is probably a way around this, but maybe the better fix is to either let JCloudScaleObjectLogger use CgLibUtil's logger or make the class non-private.

**Comment by rstzab** [comment]
The easiest workaround is to use another overload to specify this: 
<code>withLoggingCustom(String, Level)</code>

But you're right, these classes should use CgLibUtil loggers and this is like that starting with version 0.4.5-SNAPSHOT
